import Palu from '../assets/palu.webp';
const Homeproduct =
[
    {
        id: 1,
        Name: 'Palu',
        price: '120.000',
        image: 'Palu',
        cat: 'Palu',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Screwdriver',
        price: '59.000',
        image: 'image/p2.webp',
        cat: 'Screwdriver',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Bor drill impact',
        price: '1.572.000',
        image: 'image/p3.webp',
        cat: 'Bor drill impact',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Compressor',
        price: '2.705.000',
        image: 'image/p9.jpg',
        cat: 'Compressor',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Tang',
        price: '500.000',
        image: 'image/p4.webp',
        cat: 'Tang',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'Boltcutter',
        price: '590.000',
        image: 'image/p/5.webp',
        cat: 'Boltcutter',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Set Tools 24',
        price: '956.000',
        image: 'image/p10.jpg',
        cat: 'Set Tools 24',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'Set Tools 12',
        price: '389.000',
        image: 'image/p11.jpg',
        cat: 'Set Tools 12',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Jack hammer',
        price: '700.000',
        image: 'image/p6.webp',
        cat: 'Jack hammer',
        type: 'top',
    },
    {
        id: 10,
        Name: 'Nail Gun',
        price: '710.000',
        image: 'image/p7.webp',
        cat: 'Nail Gun',
        type: 'top',
    },
    {
        id: 11,
        Name: 'Impact',
        price: '170.000',
        image: 'image/p8.webp',
        cat: 'Impact',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Rolled Saw',
        price: '807.000',
        image: 'image/p12.jpg',
        cat: 'Rolled Saw',
        type: 'top',
    },
]
export default Homeproduct